services:
  - type: web
    name: rag-backend
    env: python
    buildCommand: pip install -r requirements.txt && python app/init_db.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000

